import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { TokenDapp } from '@/components/TokenDapp'
import { AlephiumConnectButton, useWallet } from '@alephium/web3-react'
import { tokenFaucetConfig } from '@/services/utils'

export default function Home() {
  const { connectionStatus } = useWallet()
  const [isModalOpen, setIsModalOpen] = React.useState(false);
  const [modalType, setModalType] = React.useState('');

  const openModal = (type: string) => {
    setModalType(type)
    setIsModalOpen(true)
  };

  const closeModal = (event: any) => {
    if (event.currentTarget === event.target) {
      setIsModalOpen(false);
    }
  };

  return (
    <>
      <div className={styles.container}>
        <div className={styles.header}>
          <AlephiumConnectButton/>
        </div>
        <div className={styles.line}></div>
        <Head>
          <title>Token Faucet</title>
          <meta name="description" content="Generated by @alephium/cli init"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <link rel="icon" href="/favicon.ico"/>
          <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"/>
        </Head>

        {connectionStatus === 'connected' && <TokenDapp config={tokenFaucetConfig}/>}

        <div className="bg-grhay-100 p-8">
          <div className="flex justify-between mb-6">
            <div className="bg-white shadow rounded p-4 w-1/2 mr-2">
              <h2 className="text-lg font-semibold mb-4">Operator</h2>
              <p>Fees: <span className="font-semibold text-gray-700">0.50 ALPH</span></p>
              <p>Address: <span className="font-mono text-gray-700">0x000123</span></p>

            </div>

            <div className="bg-white shadow rounded p-4 w-1/2 ml-2">
              <h2 className="text-lg font-semibold mb-4">Sample DApp</h2>
              <p>Address: <span className="font-mono text-gray-700">0x000</span></p>
              <p>Last Price: <span className="font-semibold text-gray-700">3.45 USD</span></p>
              <p>Current State: <span className="font-semibold text-gray-700">Waiting</span></p>
              <p>Subscription: <span className="font-mono text-gray-700">0x000</span></p>
            </div>
          </div>

          <div className="flex justify-end mb-6">
            <button
              className="inline-flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 sm:ml-3 sm:w-auto ">

              Execute
            </button>

          </div>

          {/* Logs Section */}
          <div className="bg-white shadow-lg rounded-lg p-6 mb-6">
            <h2 className="text-xl font-semibold mb-4">Logs</h2>
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                  <th scope="col" className="py-3 px-6">Date</th>
                  <th scope="col" className="py-3 px-6">From</th>
                  <th scope="col" className="py-3 px-6">To</th>
                  <th scope="col" className="py-3 px-6">ALPH</th>
                </tr>
                </thead>
                <tbody>
                {/* Repeat your rows here */}
                <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                  <td className="py-4 px-6">Date</td>
                  <td className="py-4 px-6">From</td>
                  <td className="py-4 px-6">To</td>
                  <td className="py-4 px-6">ALPH</td>
                </tr>
                {/* ...other rows */}
                </tbody>
              </table>
            </div>
          </div>

          {/* Subscriptions Section */}
          <div className="bg-white shadow-lg rounded-lg p-6 mb-6">
            <div className="flex justify-between mb-6">
            <h2 className="text-xl font-semibold ">Subscriptions</h2>
              <button
                  className="inline-flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 sm:ml-3 sm:w-auto ">
                New
              </button>

            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-gray-500 dark:text-gray-400">
                <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700">
                <tr>
                  <th scope="col" className="text-left py-3 px-6">Sub ID</th>
                  <th scope="col" className="text-left py-3 px-6">Consumers</th>
                </tr>
                </thead>
                <tbody>
                {/* Example row */}
                <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                  <td className="py-4 px-6">0x0001</td>
                  <td className="py-4 px-6">
                    <button type="button"
                            onClick={() => openModal('add')}
                            className="text-white bg-indigo-600 hover:bg-indigo-700 focus:ring-4 focus:outline-none focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-indigo-500 dark:hover:bg-indigo-600 ">Add
                    </button>
                    <button
                        onClick={() => openModal('remove')}
                        className="text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-red-500 dark:hover:bg-red-600 ">
                      Remove
                    </button>
                  </td>
                </tr>
                {/* ...other rows */}
                </tbody>
              </table>
            </div>
          </div>

          {/* ...rest of your code */}

          {isModalOpen && (
              <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full" id="my-modal"
                   onClick={closeModal}>
                <div className="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
                    <div className="mt-3 text-center">

                      <h3 className="text-lg leading-6 font-medium text-gray-900">{modalType === 'add'  ? 'Add Consumer': 'Remove Consumer'}</h3>
                      {/* Modal content */}
                      <div className="mt-2 px-7 py-3">
                        <input type="text" className="border-2 rounded p-2 w-full" placeholder="Address" />
                      </div>
                      {/* Modal footer */}
                      <div className="items-center px-4 py-3">
                        <button onClick={closeModal} className="px-4 py-2 bg-green-500 text-white text-base font-medium rounded-md w-full shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-300">
                          Submit
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
            )}

          </div>
      </div>
    </>
  )
}
